version: '3.8'

services:

  flask_app:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - app-tier
    restart: always  
    volumes:
       - ./flask/web:/app        
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app

  react_app:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-tier
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react_app
      - flask_app
    networks: 
      - app-tier
    restart: "on-failure"

networks:
  app-tier:
    driver: bridge
